backend:
  name: git-gateway
  branch: main
locale: 'fr'
publish_mode: editorial_workflow
media_folder: "_assets/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Billets" # Used in the UI
    label_singular: "Billet" # Used in the UI, ie: "New Post"
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "tags", name: "tags", widget: "hidden", default: ["blog"]}
      - {label: "Catégorie", name: "category", widget: "list", default: ["Général"]}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "pages" 
    label: "Page"
    folder: "/"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Ordre", name: "order", widget: "number"}
  - name: "livres"
    label: "Livres"
    label_singular: "Livre"
    folder: "catalogue/livres"
    create: true
    slug: "title.md"
    fields:
      - {label: "tags", name: "tags", widget: "list", default: ["coll_traversees","coll_vagabondages"]}
      - {label: "Titre du livre", name: "title", widget: "string"}
      - {label: "permalink", name: "permalink", widget: "string", default: "catalogue/changeme/"}
      - {label: "Collection", name: "book.collection", widget: "list", default: ["Traversées","Vagabondages"]}
      - {label: "Auteurice", name: "book.author", widget: "string"}
      - {label: "Date de parution", name: "book.date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Prix papier", name: "book.p_price", widget: "number", value_type: "float", required: false}
      - {label: "Prix numérique", name: "book.d_price", widget: "number", value_type: "float", required: false}
      - {label: "ISBN papier", name: "book.p_isbn", widget: "string", required: false}
      - {label: "ISBN numérique", name: "book.d_isbn", widget: "string", required: false}
      - {label: "Couverture (URL)", name: "book.cover_url", widget: "string", required: false}    
      - {label: "Lien achat papier", name: "book.p_buy_url", widget: "string", required: false}
      - {label: "Lien achat numérique Fnac", name: "book.d_buy_url_Fnac", widget: "string", required: false}
      - {label: "Lien achat numérique Kobo", name: "book.d_buy_url_Kobo", widget: "string", required: false}
      - {label: "Lien achat numérique Google", name: "book.d_buy_url_Google", widget: "string", required: false}
      - {label: "Résumé", name: "description", widget: "markdown"}