backend:
  name: git-gateway
  branch: main
locale: 'fr'
publish_mode: simple
media_folder: "_assets/uploads/images"
public_folder: "/_assets/images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Billets" # Used in the UI
    label_singular: "Billet" # Used in the UI, ie: "New Post"
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: "_assets/uploads/images/blog"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: ["blog"]}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "pages" 
    label: "Page"
    folder: "/"
    create: true
    media_folder: "_assets/uploads/images/pages"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Ordre", name: "order", widget: "number"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "livres"
    label: "Livres"
    label_singular: "Livre"
    folder: "catalogue/livres"
    create: true
    media_folder: "_assets/uploads/images/catalogue"
    slug: "{{title}}"
    fields:
      - {label: "Titre du livre", name: "title", widget: "string"}
      - {label: "permalink", name: "permalink", widget: "string", default: "catalogue/{{slug}}/"}
      - name: "book"
        collapse: true
        widget: "object"
        fields:
          - {label: "Collection", name: "collection", widget: "select", options: ["traversées", "vagabondages"]}
          - {label: "Auteurice", name: "author", widget: "list", collapsed: true}
          - {label: "Date de parution", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
          - {label: "Nombre de pages", name: "nb_pages", widget: "number", required: false}
          - label: "Couverture"
            name: "cover"
            widget: "file"
            required: false
          - {label: "Illustrateurice", name: "cover_author", widget: "list", collapsed: true}
          - name: "p"
            collapse: true
            widget: "object"
            label: "Informations livre physique"
            required: false
            fields:
              - {label: "Prix (EUR TTC)", name: "price", widget: "number", value_type: "float"}
              - {label: "ISBN", name: "isbn", widget: "string"}
              - name: "dimensions"
                label: "Dimensions"
                widget: "object"
                fields:
                  - {label: "Poids (g)", name: "weight", widget: "number", value_type: "float"}
                  - {label: "Largeur (cm)", name: "width", widget: "number", value_type: "float"}
                  - {label: "Hauteur (cm)", name: "height", widget: "number", value_type: "float"}
                  - {label: "Dos (cm)", name: "spine", widget: "number", value_type: "float"}
          - name: "d"
            collapse: true
            widget: "object"
            label: "Informations livre numérique"
            required: false
            fields:
              - {label: "Prix (EUR TTC)", name: "price", widget: "number", value_type: "float", required: false}          
              - {label: "ISBN", name: "isbn", widget: "string", required: false}
              - name: "shop"
                label: "elibrairie"
                widget: "object"
                required: false
                fields:
                  - {label: "Fnac", name: "Fnac", widget: "string"}
                  - {label: "Kobo", name: "Kobo", widget: "string"}
                  - {label: "Google", name: "Google", widget: "string"}
      - {label: "Résumé", name: "body", widget: "markdown"}