backend:
  name: git-gateway
  branch: main
media_folder: "assets/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "tags", name: "tags", widget: "hidden", default: ["blog"]}
      - {label: "Catégorie", name: "tags", widget: "list", default: ["Général"]}
      - {label: "Contenu", name: "body", widget: "markdown"}